config/routes.rb
Rails.application.routes.draw do


  resources :posts do
    resources :comments
  end

  resources :followers, except: [:edit, :update]
  

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show, :index]

  post 'users/search' => 'users#search', as: 'search_users'
  get 'expired' => 'posts#change_expired', as: 'change_expired'
  get 'followers_posts' => 'posts#followers_index', as: 'followers_index'
  get 'following_posts' => 'posts#following_index', as: 'following_index'
  get 'filter_index' => 'posts#filter', as: 'filter'

  root "posts#filter"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :post_id, :user_id

end

app/models/follower.rb
class Follower < ActiveRecord::Base

  belongs_to :following, :class_name => 'User'
  belongs_to :follower, :class_name => 'User'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates_presence_of :post_content, :user_id

  before_create :set_expired, :set_search

  def set_expired
    self.expired = Time.now + 604800 if self.expired == nil
  end

  def set_search
    self.search_post_content = self.post_content.downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :followers, :class_name => 'Follower', foreign_key: 'followed_id', :dependent => :destroy
  has_many :followings, :class_name => 'Follower', foreign_key: 'follower_id', :dependent => :destroy

  before_create :set_search

  validates_uniqueness_of :handle, :email
  validates_presence_of :handle, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                    :default_url => "https://s3.amazonaws.com/flatiron-chatter/missing.png",
                    :bucket => 'flatiron-chatter'
                    
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def set_search
    self.search_handle = self.handle.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

  private
  # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    respond_to do |format|
      format.js { }
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id
    @comment.save
    # @comment.post.comments.last
    respond_to do |format|
      format.js { }
    end
  end

  def destroy
    puts "destroyed!"
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def new
    new_follows = Follower.find_or_create_by(followed_id: params[:format], follower_id: current_user.id)
    redirect_to user_path(User.find(params[:format]))
  end

  def create
  end

  def destroy
    @follows = Follower.find(params[:id])
    @user = User.find(@follows.followed_id)
    @follows.destroy
    redirect_to user_path(@user)
  end

  def show
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def filter
    if current_user
      redirect_to following_index_path
    else
      redirect_to posts_path
    end
  end

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def new
    @post = Post.new
  end

  def change_expired
    respond_to do |format|
      format.js { }
    end
  end

  def create
    @post = Post.new(post_params)
    if params[:post][:expired] != nil
      if params[:post][:expired] == "very_soon"
        @post.expired = Time.now + 10     
      else
        @post.expired = Time.now + params[:post][:expired].to_i*24*60*60
      end
    end
    @post.user_id = current_user.id
    @post.save
    respond_to do |format|
      format.js { }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.expired < Time.now
      @post_id = @post.id
      @post.destroy
      respond_to do |format|
        format.js { }
      end
    end
  end

  def followers_index
    @user = current_user
    @followers = @user.followers.collect {|follow| User.find(follow.follower_id)}
    @posts = @followers.collect {|follower| follower.posts}
    @posts.flatten!
    @post = Post.new
    render "index"
  end

  def following_index
    @user = current_user
    @followings = @user.followings.collect {|follow| User.find(follow.followed_id)}
    @posts = @followings.collect {|follower| follower.posts}
    @posts.flatten!
    @post = Post.new
    render "index"
  end

  private
    def post_params
      params.require(:post).permit(:post_content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:name, :handle, :email, :password, :password_confirmation, :avatar)
    end

    def account_update_params
      params.require(:user).permit(:name, :handle, :email, :password, :password_confirmation, :current_password, :avatar, :bucket)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
    # check to see if current_user is already following @user
    @following_status = false
    if current_user
      if Follower.find_by(follower_id: current_user.id, followed_id: @user.id)
        @follower = Follower.find_by(follower_id: current_user.id, followed_id: @user.id)
        @following_status = true
      end
    end
    @followings = @user.followings.collect do |follower|
      User.find(follower.followed_id)
    end.uniq
    @followers = @user.followers.collect do |follower|
      User.find(follower.follower_id)
    end.uniq
  end

  def search
    @q = params[:query]
    @results = Search.search(@q)
    render :"/users/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_new.html.erb
<%= form_for @comment, url: post_comments_path do |f| %>
  <%= f.text_field :comment_content %>
  <%= f.submit "Comment", :class => 'btn btn-primary' %>
<% end %>

app/views/comments/_show_comment.html.erb
<p class="comment_content"><%= comment.comment_content %></p>
<p>From: <%= link_to "#{comment.user.handle}", user_path(comment.user) %></p>

app/views/comments/create.js.erb
$("#comment_post_<%= @comment.post.id %>").append("<%= j render partial:"show_comment", locals:{comment: @comment} %>");
$("#comment_comment_content").val("");

app/views/comments/new.html.erb
<%= form_for @comment, url: post_comments_path do |f| %>
  <%= f.label :comment_content %>
  <%= f.text_field :comment_content %>
  <%= f.submit %>
<% end %>

app/views/comments/new.js.erb
// Append the post with a comment form
// We'll need to use the post_id to attach it to the right form
// @comment has that already.
var aTag = ".commentButton[href='/posts/<%= @comment.post_id %>/comments/new']"
$(aTag).replaceWith("<%= j render partial:"new" %>")
$(".new_comment").on("submit", createComment);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared_partial/navbar" %>

<%= yield %>

</body>
</html>

app/views/posts/_change_expired.html.erb
Expire in:
<select name="post[expired]" id="post_expired">
	<option value="7">7</option>
	<option value="6">6</option>
	<option value="5">5</option>
	<option value="4">4</option>
	<option value="3">3</option>
	<option value="2">2</option>
	<option value="1">1</option>
	<option value="very_soon">VERY SOON</option>	
</select>

app/views/posts/_new.html.erb
<%= form_for @post do |f|%>
<table>
  <tr>
    <td class="post_text_field" >  <%= f.text_field :post_content %>  </td>
    <td>  <%= f.submit "Create Post", :class => 'btn btn-primary'  %></td>
  </tr>
  <tr height="50px" colspan="2"> 
      <td>      Expires in:&nbsp&nbsp
        <select name="post[expired]" id="post_expired">
        <option value="7">7</option>
        <option value="6">6</option>
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
        <option value="very_soon">VERY SOON</option>  
        </select>
      </td>
  </tr>
</table>
<% end %>

app/views/posts/_show_post.html.erb
<table class="postTable">
	<tr id="trpost_<%= post.id %>">
		<td style="background: url(<%=post.user.avatar.url %>) no-repeat center; background-size: 120px 80px; width: 180px;">
		</td>
		<td style="width: 10px;">&nbsp</td>
		<td>
		<div id="post_<%= post.id %>"class="post_div" post_id="<%= post.id %>">
			<div class="countdown">
				<span class="expiredate" value="<%= post.expired %>">Expiring in: </span>		
				<span class="days">00</span>
				<span class="timeRefDays">days</span>
				<span class="hours">00</span>
				<span class="timeRefHours">hours</span>
				<span class="minutes">00</span>
				<span class="timeRefMinutes">minutes</span>
				<span class="seconds">00</span>
				<span class="timeRefSeconds">seconds</span>
			</div>
		<p class="post_content"><%= post.post_content %></p>

		<p>by: <%= link_to "#{post.user.handle}", user_path(post.user) %></p>
		</div> 
		</td>
	</tr>
	<tr>
		<td> &nbsp </td>
		<td> &nbsp </td>		
		<td> 	
		<div id="comment_post_<%= post.id %>">
			<% post.comments.each do |comment|%>
				<%= render "/comments/show_comment", :comment => comment %>
			<% end %>
		</div>
		<% if current_user != nil %>
			<a class="commentButton" href="/posts/<%= post.id %>/comments/new">Reply</a><br> 
		<% end %>
	 </td>
	</tr>
</table>

app/views/posts/change_expired.js.erb
$(".expireSelect").replaceWith("<%= j render partial:"change_expired" %>")

app/views/posts/create.js.erb
// select the div partial will go inside of the element and prepend so it shows the most recent
$("#posts").prepend("<%= j render partial:"show_post", locals:{post: @post} %>");
$(".countdown").each(function(){
	$(this).countdown({
		date: $(this).children('.expiredate').attr("value"),
		format: "on"
	});
})
$("#post_post_content").val("");

$(".commentButton").on("click", changeReply);

app/views/posts/destroy.js.erb
// remove the deleted post from the DOM
$("#trpost_<%= @post_id %>").slideUp(function(){
	$(this).remove();
});
// refactor
//  $(this).parent().parent().parent().parent().remove();

app/views/posts/index.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
  <% if current_user != nil %>
    <div id="feed">
      <%= link_to posts_path do  %>
        <div class="btn btn-default">
          All Posts
        </div>
      <% end %>
      <%= link_to followers_index_path do %>
        <div class="btn btn-default">
          My Followers
        </div>
      <% end %>
      <%= link_to following_index_path do %>
        <div class="btn btn-default">
          Who I am Following
        </div>
      <% end %>
    </div>
    <%= render "new" %>
  <% end %>
  <br>
  <div id="posts">
	<% @posts.each do |post|%>
		<%= render "show_post", :post => post %>
	<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
	<%= f.label :post_content %>
	<%= f.text_field :post_content %>
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= render :"show", show: @post %>

app/views/shared_partial/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand"><%= link_to "Chatter", root_path%></p>
    </div>
    <%= form_tag(search_users_path, :class => "nav navbar-form navbar-left", :role => "search")  do %>
      <div class="form-group">
        <input id="searchbar" name="query" placeholder="Search chatter..." type="text">
      </div>
    <% end %>


<!--     <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a class="btn" href="<%= user_path(current_user) %>">@<%= current_user.handle%></a></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><a class="btn" href="/users/sign_up">Sign Up!</a></li>
					<li><a class="btn" href="/users/sign_in">Log In</a></li>
				<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="col-md-3"></div>
<div class="col-md-6">
	<p>You searched for <%= @q.gsub("%","") %>, here are your results:</p><br>
	<% @results.each do |result| %>
		<%= link_to "#{result.handle}", user_path(result) if result.class == User %><br>
		<% if result.class == Post %>
			<p>Post: "<%= result.post_content %>"<br>post_author: <%= link_to "#{result.user.handle}", user_path(result.user) %></p>
		<% end %>
	<% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<body>
<h2 class="handle">@<%= @user.handle %></h2>
<h2 class="username"><%= "#{@user.name}" if @user.name.length > 0 %></h2>

<p>&nbsp</p>
		<div class="circular" style="background: url(<%=@user.avatar.url %>) no-repeat center center; background-size: cover;"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
<p>&nbsp</p>
<table class="table" width="100%" cellspacing="0">
	<tr class="follow_data">
		<td>followers</td>
		<td>following</td>
	</tr>
	<tr>

		<td><% @followers.each do |follower| %>
			<%= link_to(follower.handle, user_path(follower)) %><br>  
		<% end %>
		</td>
		<td><% @followings.each do |follower| %>
			<%= link_to(follower.handle, user_path(follower)) %><br> 
		<% end %>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<% if current_user %>
			<% if @following_status %>
			<%= link_to "Unfollow", @follower, :class=>"follow_button", method: :delete %><br><br>
			<% elsif !@following_status %>
			<%= link_to "Follow", new_follower_path(@user), :class=>"follow_button" if @user != current_user %><br><br>
			<% end %>
				<%= link_to "Settings", edit_user_registration_path %>
			<% else %>
			<a href="/users/sign_up">Sign-up</a> or <a href="/users/sign_in">Log-in</a> to follow!<br><br>
			<% end %>
		</td>
	</tr>
</table>
	

	<% @user.posts.each do |post| %>
		<p>Post: <%= post.post_content %></p><br>
	<% end %>

</div>
</body>